### PR TITLE
Add assign torrent functionality

### PR DESCRIPTION
**Pull request by antonsoroko**
Adds the possibility to assign **existing** torrent to elementum's item or to kodi's library item.

"Existing" means that torrent must be already in elementum, either in "torrents history" or in active "torrents list" (by default it opens "torrents history" and you can manually navigate to "torrents list" if needed).

It implemented in such way because there are at least 3 ways to add torrent:
1. "Add Torrent" via main menu in elementum
2. "Add Torrent" via Web UI of elementum
3. "Search" via main menu in elementum (not Trakt search but general torrents search)

and it would be ineffective to implement this feature for each way separately. Also N.1 is inconvenient for tv boxes.

Also can be used to re-assign torrent - when you downloaded torrent and you did not like it but you decided to be a good person and to seed in anyway. So you can re-assign new one while keeping old and old torrent will not pop-up in UI when you play item.

Tested on Kodi 19 and 17.

depends on https://github.com/elgatito/elementum/pull/38

---
fixes https://github.com/elgatito/plugin.video.elementum/issues/100
fixes https://github.com/elgatito/plugin.video.elementum/issues/619
indirectly fixes https://github.com/elgatito/plugin.video.elementum/issues/692
mitigate severeness of https://github.com/elgatito/plugin.video.elementum/issues/676

### CODE REVIEW

**Comment by antonsoroko** [comment]
по желанию, можно ещё удалить старый неиспользуемый код, для чистоты.

**Comment by antonsoroko** [comment]
@elgatito мержим? или есть замечания по коду?

**Comment by elgatito** [comment]
@antonsoroko Sorry, forgot about this one.

**Comment by antonsoroko** [comment]
спасибо. ед момент, надо бы ещё тогда и демон зарелизить (чтобы были доступны соответствующие изменения).

**Pull request merged**
